In [16]:
# List of words to pair with products
words = ["buy","price","discount","promotion","promo","shop","sofas","beds","seats"]

# Print list of words
print(words)

['buy', 'price', 'discount', 'promotion', 'promo', 'shop', 'sofas', 'beds', 'seats']

In [17]:
products = ['sofas', 'convertible sofas', 'love seats', 'recliners', 'sofa beds']

# Create an empty list
keywords_list = []

# Loop through products
for product in products:
    # Loop through words
    for word in words:
        # Append combinations
        keywords_list.append([product, product + ' ' + word])
        keywords_list.append([product, word + ' ' + product])
        
# Inspect keyword list
from pprint import pprint
pprint(keywords_list)

[['sofas', 'sofas buy'],
 ['sofas', 'buy sofas'],
 ['sofas', 'sofas price'],
 ['sofas', 'price sofas'],
 ['sofas', 'sofas discount'],
 ['sofas', 'discount sofas'],
 ['sofas', 'sofas promotion'],
 ['sofas', 'promotion sofas'],
 ['sofas', 'sofas promo'],
 ['sofas', 'promo sofas'],
 ['sofas', 'sofas shop'],
 ['sofas', 'shop sofas'],
 ['sofas', 'sofas sofas'],
 ['sofas', 'sofas sofas'],
 ['sofas', 'sofas beds'],
 ['sofas', 'beds sofas'],
 ['sofas', 'sofas seats'],
 ['sofas', 'seats sofas'],
 ['convertible sofas', 'convertible sofas buy'],
 ['convertible sofas', 'buy convertible sofas'],
 ['convertible sofas', 'convertible sofas price'],
 ['convertible sofas', 'price convertible sofas'],
 ['convertible sofas', 'convertible sofas discount'],
 ['convertible sofas', 'discount convertible sofas'],
 ['convertible sofas', 'convertible sofas promotion'],
 ['convertible sofas', 'promotion convertible sofas'],
 ['convertible sofas', 'convertible sofas promo'],
 ['convertible sofas', 'promo convertible sofas'],
 ['convertible sofas', 'convertible sofas shop'],
 ['convertible sofas', 'shop convertible sofas'],
 ['convertible sofas', 'convertible sofas sofas'],
 ['convertible sofas', 'sofas convertible sofas'],
 ['convertible sofas', 'convertible sofas beds'],
 ['convertible sofas', 'beds convertible sofas'],
 ['convertible sofas', 'convertible sofas seats'],
 ['convertible sofas', 'seats convertible sofas'],
 ['love seats', 'love seats buy'],
 ['love seats', 'buy love seats'],
 ['love seats', 'love seats price'],
 ['love seats', 'price love seats'],
 ['love seats', 'love seats discount'],
 ['love seats', 'discount love seats'],
 ['love seats', 'love seats promotion'],
 ['love seats', 'promotion love seats'],
 ['love seats', 'love seats promo'],
 ['love seats', 'promo love seats'],
 ['love seats', 'love seats shop'],
 ['love seats', 'shop love seats'],
 ['love seats', 'love seats sofas'],
 ['love seats', 'sofas love seats'],
 ['love seats', 'love seats beds'],
 ['love seats', 'beds love seats'],
 ['love seats', 'love seats seats'],
 ['love seats', 'seats love seats'],
 ['recliners', 'recliners buy'],
 ['recliners', 'buy recliners'],
 ['recliners', 'recliners price'],
 ['recliners', 'price recliners'],
 ['recliners', 'recliners discount'],
 ['recliners', 'discount recliners'],
 ['recliners', 'recliners promotion'],
 ['recliners', 'promotion recliners'],
 ['recliners', 'recliners promo'],
 ['recliners', 'promo recliners'],
 ['recliners', 'recliners shop'],
 ['recliners', 'shop recliners'],
 ['recliners', 'recliners sofas'],
 ['recliners', 'sofas recliners'],
 ['recliners', 'recliners beds'],
 ['recliners', 'beds recliners'],
 ['recliners', 'recliners seats'],
 ['recliners', 'seats recliners'],
 ['sofa beds', 'sofa beds buy'],
 ['sofa beds', 'buy sofa beds'],
 ['sofa beds', 'sofa beds price'],
 ['sofa beds', 'price sofa beds'],
 ['sofa beds', 'sofa beds discount'],
 ['sofa beds', 'discount sofa beds'],
 ['sofa beds', 'sofa beds promotion'],
 ['sofa beds', 'promotion sofa beds'],
 ['sofa beds', 'sofa beds promo'],
 ['sofa beds', 'promo sofa beds'],
 ['sofa beds', 'sofa beds shop'],
 ['sofa beds', 'shop sofa beds'],
 ['sofa beds', 'sofa beds sofas'],
 ['sofa beds', 'sofas sofa beds'],
 ['sofa beds', 'sofa beds beds'],
 ['sofa beds', 'beds sofa beds'],
 ['sofa beds', 'sofa beds seats'],
 ['sofa beds', 'seats sofa beds']]

In [18]:
# Load library
# ... YOUR CODE FOR TASK 3 ...
import pandas as pd 
# Create a DataFrame from list
keywords_df = pd.DataFrame.from_records(keywords_list)

# Print the keywords DataFrame to explore it
keywords_df.head()

       0               1
0  sofas       sofas buy
1  sofas       buy sofas
2  sofas     sofas price
3  sofas     price sofas
4  sofas  sofas discount

In [19]:
# Rename the columns of the DataFrame
keywords_df = keywords_df.rename(columns={0:'Ad Group',1:'Keyword'})
keywords_df

     Ad Group          Keyword
0       sofas        sofas buy
1       sofas        buy sofas
2       sofas      sofas price
3       sofas      price sofas
4       sofas   sofas discount
..        ...              ...
85  sofa beds  sofas sofa beds
86  sofa beds   sofa beds beds
87  sofa beds   beds sofa beds
88  sofa beds  sofa beds seats
89  sofa beds  seats sofa beds

[90 rows x 2 columns]

In [20]:
keywords_df['Campaign'] = 'SEM_Sofas'
keywords_df

     Ad Group          Keyword   Campaign
0       sofas        sofas buy  SEM_Sofas
1       sofas        buy sofas  SEM_Sofas
2       sofas      sofas price  SEM_Sofas
3       sofas      price sofas  SEM_Sofas
4       sofas   sofas discount  SEM_Sofas
..        ...              ...        ...
85  sofa beds  sofas sofa beds  SEM_Sofas
86  sofa beds   sofa beds beds  SEM_Sofas
87  sofa beds   beds sofa beds  SEM_Sofas
88  sofa beds  sofa beds seats  SEM_Sofas
89  sofa beds  seats sofa beds  SEM_Sofas

[90 rows x 3 columns]

In [21]:
# Add a criterion type column
keywords_df['Criterion Type'] = 'Exact'
keywords_df

     Ad Group          Keyword   Campaign Criterion Type
0       sofas        sofas buy  SEM_Sofas          Exact
1       sofas        buy sofas  SEM_Sofas          Exact
2       sofas      sofas price  SEM_Sofas          Exact
3       sofas      price sofas  SEM_Sofas          Exact
4       sofas   sofas discount  SEM_Sofas          Exact
..        ...              ...        ...            ...
85  sofa beds  sofas sofa beds  SEM_Sofas          Exact
86  sofa beds   sofa beds beds  SEM_Sofas          Exact
87  sofa beds   beds sofa beds  SEM_Sofas          Exact
88  sofa beds  sofa beds seats  SEM_Sofas          Exact
89  sofa beds  seats sofa beds  SEM_Sofas          Exact

[90 rows x 4 columns]

In [22]:
# Make a copy of the keywords DataFrame
keywords_phrase = keywords_df.copy()

# Change criterion type match to phrase
keywords_df['Criterion Type'] = 'Phrase'
# ... YOUR CODE FOR TASK 7 ...

# Append the DataFrames
keywords_df_final =keywords_df.merge(keywords_phrase)
keywords_df_final

Empty DataFrame
Columns: [Ad Group, Keyword, Campaign, Criterion Type]
Index: []